name: Release

on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:

concurrency:
   group: "release"
   cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup NodeJS 17
        uses: actions/setup-node@v3
        with:
          node-version: "17"

      - name: Install node modules
        run: npm install

      - name: Build Project
        run: npm run release

      - name: Get System ID
        id: systemID
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'system.json'
          prop_path: 'id'

      - name: Create ZIP
        run: |
          cd build
          zip -r ../${{steps.systemID.outputs.prop}}.zip *

      - name: Set Download Link
        uses: jossef/action-set-json-field@v2
        with:
          file: './system.json'
          field: 'download'
          value: "https://github.com/${{github.repository}}/releases/download/${{github.run_number}}/${{steps.systemID.outputs.prop}}.zip"

      -  name: Create Release
         run: |
            hub release create -a ./${{steps.systemID.outputs.prop}}.zip -a ./system.json -m "dev build ${{github.run_number}}" ${{github.run_number}}
         env:
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
