name: Dev Build

on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:

concurrency:
   group: "release"
   cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup NodeJS 17
        uses: actions/setup-node@v3
        with:
          node-version: "17"

      - name: Install node modules
        run: npm install

      - name: Build Project
        run: npm run release

      - name: Get System ID
        id: systemID
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'system.json'
          prop_path: 'id'

      - name: Create ZIP
        run: |
          cd build
          zip -r ../${{steps.systemID.outputs.prop}}.zip *

      - name: Set Manifest Link
        uses: jossef/action-set-json-field@v2
        with:
          file: './system.json'
          field: 'manifest'
          value: "https://github.com/${{github.repository}}/releases/releases/latest/download/system.json"

      - name: Set Download Link
        uses: jossef/action-set-json-field@v2
        with:
          file: './system.json'
          field: 'download'
          value: "https://github.com/${{github.repository}}/releases/download/dev-${{github.run_number}}/${{steps.systemID.outputs.prop}}.zip"

      - name: Set URL
        uses: jossef/action-set-json-field@v2
        with:
          file: './system.json'
          field: 'url'
          value: "https://github.com/${{github.repository}}"

      -  name: Create Release
         run: |
            TAG_NAME="v1.0.0-beta"
            RELEASE_NAME="Beta Release"

            # Create the release
            gh release create "dev-${{github.run_number}}" --title "dev-${{github.run_number}}" --notes "dev build ${{github.run_number}}" --prerelease ./${{steps.systemID.outputs.prop}}.zip ./system.json
         env:
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

